"""add partial unique index for users email

Revision ID: 0986990a0d61
Revises: 8bd35b828e6c
Create Date: 2026-01-16 18:28:11.826600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0986990a0d61'
down_revision: Union[str, Sequence[str], None] = '8bd35b828e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE UNIQUE INDEX uniq_active_users_email
        ON users (email)
        WHERE is_active = true;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP INDEX IF EXISTS uniq_active_users_email;
        """
    )
    # ### end Alembic commands ###
