"""Tasks_Code: template & func_name nullable

Revision ID: 2928f5e43fad
Revises: 14f8addbbbb1
Create Date: 2026-03-03 18:26:08.602667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2928f5e43fad'
down_revision: Union[str, Sequence[str], None] = '14f8addbbbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks_code', 'template',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks_code', 'func_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks_code', 'func_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('tasks_code', 'template',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
