"""update models

Revision ID: 377bdd34a429
Revises: 29361eaffd60
Create Date: 2025-10-14 14:09:27.591315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377bdd34a429'
down_revision: Union[str, Sequence[str], None] = '29361eaffd60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('tasks', 'hint',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tests', 'input_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tests', 'output_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tests', 'input_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tests', 'expected_output_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('picture_link', sa.String(), nullable=True))
    op.add_column('users_stats', sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users_stats', sa.Column('streak', sa.Integer(), nullable=False))
    op.add_column('users_stats', sa.Column('total_xp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_stats', 'total_xp')
    op.drop_column('users_stats', 'streak')
    op.drop_column('users_stats', 'last_activity')
    op.drop_column('users', 'picture_link')
    op.alter_column('tests', 'expected_output_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tests', 'input_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tests', 'output_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tests', 'input_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'hint',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('levels', 'description')
    # ### end Alembic commands ###
