"""Add icon to Courses

Revision ID: 4151c52bb8a9
Revises: 7b4394241fa7
Create Date: 2026-05-07 22:00:56.869712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4151c52bb8a9'
down_revision: Union[str, Sequence[str], None] = '7b4394241fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'icon')
    # ### end Alembic commands ###
