"""Users_Stats last_activity стало None

Revision ID: 4719dbdab43c
Revises: 377bdd34a429
Create Date: 2025-10-18 15:23:57.488538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4719dbdab43c'
down_revision: Union[str, Sequence[str], None] = '377bdd34a429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
