"""Add template & func_name to Tasks

Revision ID: 50a9fb59f32c
Revises: ef685822dd7c
Create Date: 2025-12-20 16:50:45.089317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a9fb59f32c'
down_revision: Union[str, Sequence[str], None] = 'ef685822dd7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('template', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('func_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'func_name')
    op.drop_column('tasks', 'template')
    # ### end Alembic commands ###
