"""Update field code_id to nullable false

Revision ID: 7583ec4a3fc1
Revises: bcfd2610717d
Create Date: 2026-02-13 17:59:40.039658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7583ec4a3fc1'
down_revision: Union[str, Sequence[str], None] = 'bcfd2610717d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'code_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'code_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
