"""add num_in_order in Levels & edit in Level_Tasks

Revision ID: 7b4394241fa7
Revises: 2928f5e43fad
Create Date: 2026-03-16 18:10:50.019059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4394241fa7'
down_revision: Union[str, Sequence[str], None] = '2928f5e43fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('num_in_order', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'num_in_order')
    # ### end Alembic commands ###
