"""Add new T: Languages, Tasks_Code. Update Tasks, Tests

Revision ID: bcfd2610717d
Revises: 0986990a0d61
Create Date: 2026-02-13 15:27:24.407680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcfd2610717d'
down_revision: Union[str, Sequence[str], None] = '0986990a0d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('func_name', sa.String(length=80), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('tasks', 'func_name')
    op.drop_column('tasks', 'template')
    op.add_column('tests', sa.Column('code_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('tests_task_id_fkey'), 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'tasks_code', ['code_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tests', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key(op.f('tests_task_id_fkey'), 'tests', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tests', 'code_id')
    op.add_column('tasks', sa.Column('template', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('func_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('tasks_code')
    op.drop_table('languages')
    # ### end Alembic commands ###
