"""adding casccade delete to all tables

Revision ID: 9d2d357c58f7
Revises: 4719dbdab43c
Create Date: 2025-10-30 12:13:03.372691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2d357c58f7'
down_revision: Union[str, Sequence[str], None] = '4719dbdab43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('level_tasks_task_id_fkey'), 'level_tasks', type_='foreignkey')
    op.drop_constraint(op.f('level_tasks_level_id_fkey'), 'level_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'level_tasks', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'level_tasks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('levels_theory_id_fkey'), 'levels', type_='foreignkey')
    op.create_foreign_key(None, 'levels', 'theories', ['theory_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_task_type_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'tasks_types', ['task_type'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('tasks_gap_task_id_fkey'), 'tasks_gap', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_gap', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_options_task_id_fkey'), 'tasks_options', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_options', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tests_input_type_id_fkey'), 'tests', type_='foreignkey')
    op.drop_constraint(op.f('tests_output_type_id_fkey'), 'tests', type_='foreignkey')
    op.drop_constraint(op.f('tests_task_id_fkey'), 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'data_types', ['output_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tests', 'data_types', ['input_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tests', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_levels_level_id_fkey'), 'users_levels', type_='foreignkey')
    op.drop_constraint(op.f('users_levels_user_id_fkey'), 'users_levels', type_='foreignkey')
    op.create_foreign_key(None, 'users_levels', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_levels', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'users_stats', ['user_id'])
    op.drop_constraint(op.f('users_stats_user_id_fkey'), 'users_stats', type_='foreignkey')
    op.create_foreign_key(None, 'users_stats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_stats', type_='foreignkey')
    op.create_foreign_key(op.f('users_stats_user_id_fkey'), 'users_stats', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'users_stats', type_='unique')
    op.drop_constraint(None, 'users_levels', type_='foreignkey')
    op.drop_constraint(None, 'users_levels', type_='foreignkey')
    op.create_foreign_key(op.f('users_levels_user_id_fkey'), 'users_levels', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('users_levels_level_id_fkey'), 'users_levels', 'levels', ['level_id'], ['id'])
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key(op.f('tests_task_id_fkey'), 'tests', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('tests_output_type_id_fkey'), 'tests', 'data_types', ['output_type_id'], ['id'])
    op.create_foreign_key(op.f('tests_input_type_id_fkey'), 'tests', 'data_types', ['input_type_id'], ['id'])
    op.drop_constraint(None, 'tasks_options', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_options_task_id_fkey'), 'tasks_options', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'tasks_gap', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_gap_task_id_fkey'), 'tasks_gap', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_task_type_fkey'), 'tasks', 'tasks_types', ['task_type'], ['id'])
    op.drop_constraint(None, 'levels', type_='foreignkey')
    op.create_foreign_key(op.f('levels_theory_id_fkey'), 'levels', 'theories', ['theory_id'], ['id'])
    op.drop_constraint(None, 'level_tasks', type_='foreignkey')
    op.drop_constraint(None, 'level_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('level_tasks_level_id_fkey'), 'level_tasks', 'levels', ['level_id'], ['id'])
    op.create_foreign_key(op.f('level_tasks_task_id_fkey'), 'level_tasks', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
